AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
      - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
      - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      RoleName: renderRole
  RenderHome:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderHome
      CodeUri: s3://aws-sam-template-stack/010cd93eb2cefe156f227ef5160c9daf
      Description: Returns user home page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
