AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
      - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
      - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      RoleName: renderRole
  RenderHome:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderHome
      CodeUri: s3://aws-sam-template-stack/ce54e427c9e618faae9c89bd44723af5
      Description: Returns user home page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderProfile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderProfile
      CodeUri: s3://aws-sam-template-stack/7424f418452b9432207996a044f9deeb
      Description: Returns user proofile page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderUpdateProfile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderUpdateProfile
      CodeUri: s3://aws-sam-template-stack/0f528f82b255d28ffc74d840bbaffd3a
      Description: Returns update user proofile page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderIndex:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderIndex
      CodeUri: s3://aws-sam-template-stack/ecf877f6fd3c43c0cf563d41fd2b28c9
      Description: Returns update user Index page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderEvent
      CodeUri: s3://aws-sam-template-stack/e7e043dbefe94ac6c5d6376dd93fa3a5
      Description: Returns event page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
