AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/CloudWatchFullAccess
      - arn:aws:iam::aws:policy/AmazonOpenSearchServiceFullAccess
      - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
      - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      RoleName: renderRole
  RenderHome:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderHome
      CodeUri: s3://aws-sam-template-stack/2b8a48bd637d47adcf08bd31f79d5c6d
      Description: Returns user home page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderProfile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderProfile
      CodeUri: s3://aws-sam-template-stack/810baf9258958999d800f6f583cee2d1
      Description: Returns user proofile page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderUpdateProfile:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderUpdateProfile
      CodeUri: s3://aws-sam-template-stack/3b2a0edfa4c896a36105a8a94a23ed67
      Description: Returns update user proofile page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
  RenderEvent:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RenderEvent
      CodeUri: s3://aws-sam-template-stack/23e71f83a9f20a48971aab433eaff3c9
      Description: Returns event page
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role:
        Fn::GetAtt:
        - iamRole
        - Arn
      Timeout: 600
