AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  RenderHome:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: RenderHome
        CodeUri: ./render-home/
        Description: Returns user home page
        Handler: lambda_function.lambda_handler
        Runtime: python3.9
        Role: !GetAtt iamRole.Arn
        Timeout: 600
        Events:
          RenderAPI:
            Type: Api 
            Properties:
                RestApiId: !Ref RenderAPI
                Path: /home

                Method: get

  RenderEvent:
    Type: AWS::Serverless::Function
    Properties:
        FunctionName: RenderEvent
        CodeUri: ./render-event/
        Description: Returns event page
        Handler: lambda_function.lambda_handler
        Runtime: python3.9
        Role: !GetAtt iamRole.Arn
        Timeout: 600
        Events:
          RenderAPI:
            Type: Api 
            Properties:
                RestApiId: !Ref RenderAPI
                Path: /event
                Method: get
  
    RenderProfile:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName: RenderProfile
          CodeUri: ./render-profile/
          Description: Returns profile page
          Handler: lambda_function.lambda_handler
          Runtime: python3.9
          Role: !GetAtt iamRole.Arn
          Timeout: 600
          Events:
            RenderAPI:
              Type: Api 
              Properties:
                  RestApiId: !Ref RenderAPI
                  Path: /profile
                  Method: get

    RenderDiscussions:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName: RenderDiscussions
          CodeUri: ./render-discussion/
          Description: Returns discussion page
          Handler: lambda_function.lambda_handler
          Runtime: python3.9
          Role: !GetAtt iamRole.Arn
          Timeout: 600
          Events:
            RenderAPI:
              Type: Api 
              Properties:
                  RestApiId: !Ref RenderAPI
                  Path: /discussions
                  Method: get

    RenderUpdateProfile:
      Type: AWS::Serverless::Function
      Properties:
          FunctionName: RenderUpdateProfile
          CodeUri: ./render-update-profile/
          Description: Returns profile update page
          Handler: lambda_function.lambda_handler
          Runtime: python3.9
          Role: !GetAtt iamRole.Arn
          Timeout: 600
          Events:
            RenderAPI:
              Type: Api 
              Properties:
                  RestApiId: !Ref RenderAPI
                  Path: /update_profile
                  Method: get